Rest API with GET,POST,DELETE
jne-freshers-dec-2023/renuka-spring-boot pull request #7
Opened 2024-01-15 14:24 UTC by renukaThink

2024-01-15 16:30 UTC, abhaythink requested changes

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +       return user;
Please check https://docs.oracle.com/javase/8/docs/api/java/util/Optional.html

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +    }
What if User with provided id do not exists?
Handle it gracefully!

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +    public ResponseEntity<Users> createUse(@Validated @RequestBody Users user){
Can we say `User` instead of `Users`?

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +//                .toUri();
Please remove if not needed

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/exception/ResponseEntityException.java
> +    @ExceptionHandler(userNotFoundException.class)
Why `userNotFoundException` is in camel case?

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/model/Users.java
> +    }
Try to use lombok instead

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/model/Users.java
> +    @Override
Try to use lombok instead

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/services/UsersServices.java
> +       return  users.stream().filter(predicate).findFirst().orElse(null);
Good :+1:

2024-01-15 16:30 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/services/UsersServices.java
> +        return null;
Never return null anywhere. **Never**
It creates null pointer exception

2024-01-16 07:00 UTC, renukaThink commented on day-6/src/main/java/com/restapiday6/day6/social/exception/ResponseEntityException.java
> +    @ExceptionHandler(userNotFoundException.class)
updated

2024-01-16 07:00 UTC, renukaThink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +    public ResponseEntity<Users> createUse(@Validated @RequestBody Users user){
Yes we can use. It indicates that there is a collection of Users, in which we are looking for a particular user id

2024-01-16 07:06 UTC, renukaThink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserResource.java
> +    }
updated

2024-01-16 07:56 UTC, abhaythink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserController.java
> +        service.deleteById(id);
Can we  orElse() or orElseThrow()  here?

2024-01-16 07:56 UTC, abhaythink approved these changes

2024-01-16 07:58 UTC, renukaThink commented on day-6/src/main/java/com/restapiday6/day6/social/controller/UserController.java
> +        service.deleteById(id);
we can use orElseThrow()

2024-01-19 14:03 UTC, merged